### ISSUE TITLE
Can it be compatible with fabrictailor?

### ISSUE THREAD

**Issue by sadlyborger** [Mr-Zombii/MostlyServerSideCapes#1]
As what I requested.
Can it be compatible with fabrictailor?
It seems that cracked minecraft can't use fabrictailor.
Would it be possible for you?

**Comment by Mr-Zombii** [comment]
I can try to add compat with fabric tailor for you and I will also accept any requests to downgrade it if you want.

**Comment by Mr-Zombii** [comment]
May I ask, What is broken?
or is it that you want the ability to add skins to This mod?

**Comment by Mr-Zombii** [comment]
I have added skin changing support to the mod version \/
https://modrinth.com/mod/mostly-server-side-capes/version/2.0.0
and its usage is shown here \/
https://modrinth.com/mod/mostly-server-side-capes

**Comment by sadlyborger** [comment]
I will check it out and test on our server. Thank you very much. 
What was the error before was, when we use the fabric tailor on cracked client. There will be a problem on client and would give us an error, I have read that fabric tailor doesn't support cracked client.
Fabric tailor has a cape changer too, but its connected to skin and cape.
So I added your cape changing to our server, to check if it works. But it just return back to normal skin(steve), though we can use cape and change it, but still our skin return to default.

**Comment by Mr-Zombii** [comment]
Oh, I added skin changing functionality by itself to the cape mod since it would be difficult to add real compat with fabric tailor.

you can do /cape for the capes and /skin for the skins and no fabric tailor needed.

**Comment by Mr-Zombii** [comment]
or I can put both commands under a subcommand as /mssc cape {} {} and /mssc skin {} {} so it wouldn't clash with fabric tailor

I think I found a way to add compat to fabric tailor.

**Comment by Mr-Zombii** [comment]
Finished its compat, there are some bugs I have no idea how to fix with skins that can be fixed (eventually) by leaving and rejoining the server, and if it does not fix just change your skin or cape.

https://modrinth.com/mod/mostly-server-side-capes/version/oeRiGatc

**Comment by sadlyborger** [comment]
@Mr-Zombii 
Thank you very much. I really appreciate it. <3 Hope you have a good day and enjoy.
I was wondering though I have to manually add skins on my server folder for other player to use it right?

**Comment by Mr-Zombii** [comment]
Yw, also yo do not have to manually add skins in the server folder, they can just use `/mostlyserversidecapes skins {blahblah}` or fabrictailor's command for skins.
